"""Derived layer: indexes, closure, designations, passes, queries and rows (design/derive.md)."""

from fransys_model.layout import profile_of
from fransys_model.vocab import (
    Aspect,
    AspectNode,
    Boundary,
    Conductor,
    ConductorKind,
    Function,
    FunctionKind,
    Item,
    Net,
    NetClass,
    Operating,
    Placement,
    Port,
    PortRole,
    PowerKind,
    Rating,
    SupplySystem,
    Unit,
    UnitRelease,
    boundary_operating,
    boundary_rating,
    cable_items,
    function_operating,
    function_rating,
    is_cable,
    part_rating,
)
from fransys_model.vocab.energy_flow import gives_energy, takes_energy
from fransys_model.vocab.load_limits import LoadLimit, load_limits
from fransys_model.vocab.prospective_fault import ProspectiveFault, prospective_fault
from fransys_model.vocab.tables import (
    aspect_nodes,
    boundaries,
    conductors,
    functions,
    items,
    nets,
    placements,
    ports,
    supply_systems,
    unit_releases,
    units,
)

from .bom import TopLevelScope
from .box_lines import connector_box_lines
from .closure import PhysicalNet, net_of, physical_nets, port_rails, rail_pairs
from .columns import (
    BOM_COLUMNS,
    CABLE_LIST_COLUMNS,
    CONNECTOR_COLUMNS,
    CONTENTS_COLUMNS,
    DESIGNATION_COLUMNS,
    PIN_COLUMNS,
    PLC_COLUMNS,
    TERMINAL_COLUMNS,
    TERMINAL_LABELS,
    WIRE_COLUMNS,
    WIRE_LABELS,
)
from .contact_entries import NO_PLACE
from .contacts import LinkState, Throws, changeover_throws, link_state, owned_contacts
from .current_chains import CurrentBound, CurrentChain, CurrentPosition, LimitRole, current_chains
from .designation import (
    bom_sort_key,
    connector_label,
    connector_segments,
    designation_holder,
    function_designation,
    is_own_unit_root,
    item_designation,
    item_label,
    location_node_designation,
    own_nodes,
    port_designation,
    printed_designation,
    reference_designation,
    takes_parents_designation,
    unit_location,
)
from .external import external
from .harness_line_ends import harness_line_ends
from .indexes import Indexes, build_indexes
from .line_end_fact import connector_at_line_end
from .line_fact import draws_as_line, line_conductors
from .line_text import line_designation, line_stub_line
from .list_cells import (
    CELL_SEPARATOR,
    cell_parts,
    cell_text,
    column_rows,
    column_values,
    pin_lines,
)
from .lookups import black_box_unit, connector_facets, item_of_port, pin_order, terminal_items
from .mate_rows import mates
from .natural_order import natural_key
from .pairing import BoxPair, box_pairs
from .part_functions import part_function_rows
from .passes.numbering import number
from .passes.plc_allocation import allocate_plc
from .potential import port_potential_current, port_potential_rank
from .power import is_rail_terminal, port_power_kind, port_power_text, power_kind, power_text
from .queries import (
    TOP_LEVEL,
    board_netlist,
    boards,
    bom_lines,
    boundary,
    cable_list_rows,
    cable_rows,
    cable_title,
    conductors_on_item,
    connector_rows,
    contents_rows,
    core_colour,
    current_revision,
    designation_list,
    document_unit,
    drawing_set_is_replica_only,
    effective_placement,
    enclosing_boards,
    ext_usage,
    first_leg,
    harness_cables,
    harness_wires,
    is_black_box_item,
    is_plc_module,
    is_sole_unit_root,
    item_description,
    item_location,
    items_at,
    list_context,
    no_conductor_at,
    overview_graph,
    plc_channel_rows,
    plc_rack_modules,
    release_order,
    revision_history,
    revision_text,
    same_version,
    schematic_functions,
    standalone,
    subtree,
    terminal_rows,
    terminal_strips,
    top_level_cables,
    unconnected_ports,
    unit_boards,
    unit_cables,
    unit_items,
    unit_release,
    unit_strips,
    unit_subtree,
    unused_terminals,
    wire_rows,
)
from .rows import (
    BoardNetlist,
    BomLine,
    CableListRow,
    CableRow,
    ChannelScaling,
    ConnectorPin,
    ConnectorRow,
    ContentsRow,
    DesignationRow,
    ExtUsage,
    HarnessCable,
    HarnessCore,
    HarnessEnd,
    HarnessLineEnd,
    HarnessPin,
    MateRow,
    NetlistNet,
    NetlistPart,
    OverviewGraph,
    OverviewLink,
    OverviewLinkKind,
    OverviewNode,
    OverviewPort,
    OverviewSignal,
    PartFunctionRow,
    PlcChannelRow,
    PlcRackChannel,
    PlcRackModule,
    TerminalRow,
    WireRow,
)
from .side_hint_findings import check_side_hints
from .supply_share import supply_share
from .unused import function_is_unused, port_is_unused

__all__ = [
    "BOM_COLUMNS",
    "CABLE_LIST_COLUMNS",
    "CELL_SEPARATOR",
    "CONNECTOR_COLUMNS",
    "CONTENTS_COLUMNS",
    "DESIGNATION_COLUMNS",
    "NO_PLACE",
    "PIN_COLUMNS",
    "PLC_COLUMNS",
    "TERMINAL_COLUMNS",
    "TERMINAL_LABELS",
    "TOP_LEVEL",
    "WIRE_COLUMNS",
    "WIRE_LABELS",
    "Aspect",
    "AspectNode",
    "BoardNetlist",
    "BomLine",
    "Boundary",
    "BoxPair",
    "CableListRow",
    "CableRow",
    "ChannelScaling",
    "Conductor",
    "ConductorKind",
    "ConnectorPin",
    "ConnectorRow",
    "ContentsRow",
    "CurrentBound",
    "CurrentChain",
    "CurrentPosition",
    "DesignationRow",
    "ExtUsage",
    "Function",
    "FunctionKind",
    "HarnessCable",
    "HarnessCore",
    "HarnessEnd",
    "HarnessLineEnd",
    "HarnessPin",
    "Indexes",
    "Item",
    "LimitRole",
    "LinkState",
    "LoadLimit",
    "MateRow",
    "Net",
    "NetClass",
    "NetlistNet",
    "NetlistPart",
    "Operating",
    "OverviewGraph",
    "OverviewLink",
    "OverviewLinkKind",
    "OverviewNode",
    "OverviewPort",
    "OverviewSignal",
    "PartFunctionRow",
    "PhysicalNet",
    "Placement",
    "PlcChannelRow",
    "PlcRackChannel",
    "PlcRackModule",
    "Port",
    "PortRole",
    "PowerKind",
    "ProspectiveFault",
    "Rating",
    "SupplySystem",
    "TerminalRow",
    "Throws",
    "TopLevelScope",
    "Unit",
    "UnitRelease",
    "WireRow",
    "allocate_plc",
    "aspect_nodes",
    "black_box_unit",
    "board_netlist",
    "boards",
    "bom_lines",
    "bom_sort_key",
    "boundaries",
    "boundary",
    "boundary_operating",
    "boundary_rating",
    "box_pairs",
    "build_indexes",
    "cable_items",
    "cable_list_rows",
    "cable_rows",
    "cable_title",
    "cell_parts",
    "cell_text",
    "changeover_throws",
    "check_side_hints",
    "column_rows",
    "column_values",
    "conductors",
    "conductors_on_item",
    "connector_at_line_end",
    "connector_box_lines",
    "connector_facets",
    "connector_label",
    "connector_rows",
    "connector_segments",
    "contents_rows",
    "core_colour",
    "current_chains",
    "current_revision",
    "designation_holder",
    "designation_list",
    "document_unit",
    "drawing_set_is_replica_only",
    "draws_as_line",
    "effective_placement",
    "enclosing_boards",
    "ext_usage",
    "external",
    "first_leg",
    "function_designation",
    "function_is_unused",
    "function_operating",
    "function_rating",
    "functions",
    "gives_energy",
    "harness_cables",
    "harness_line_ends",
    "harness_wires",
    "is_black_box_item",
    "is_cable",
    "is_own_unit_root",
    "is_plc_module",
    "is_rail_terminal",
    "is_sole_unit_root",
    "item_description",
    "item_designation",
    "item_label",
    "item_location",
    "item_of_port",
    "items",
    "items_at",
    "line_conductors",
    "line_designation",
    "line_stub_line",
    "link_state",
    "list_context",
    "load_limits",
    "location_node_designation",
    "mates",
    "natural_key",
    "net_of",
    "nets",
    "no_conductor_at",
    "number",
    "overview_graph",
    "own_nodes",
    "owned_contacts",
    "part_function_rows",
    "part_rating",
    "physical_nets",
    "pin_lines",
    "pin_order",
    "placements",
    "plc_channel_rows",
    "plc_rack_modules",
    "port_designation",
    "port_is_unused",
    "port_potential_current",
    "port_potential_rank",
    "port_power_kind",
    "port_power_text",
    "port_rails",
    "ports",
    "power_kind",
    "power_text",
    "printed_designation",
    "profile_of",
    "prospective_fault",
    "rail_pairs",
    "reference_designation",
    "release_order",
    "revision_history",
    "revision_text",
    "same_version",
    "schematic_functions",
    "standalone",
    "subtree",
    "supply_share",
    "supply_systems",
    "takes_energy",
    "takes_parents_designation",
    "terminal_items",
    "terminal_rows",
    "terminal_strips",
    "top_level_cables",
    "unconnected_ports",
    "unit_boards",
    "unit_cables",
    "unit_items",
    "unit_location",
    "unit_release",
    "unit_releases",
    "unit_strips",
    "unit_subtree",
    "units",
    "unused_terminals",
    "wire_rows",
]
