"""Domain layer: record kinds, facets, validators, built on kernel."""

from fransys_model.kernel import register_namespaces

from .aspects import AspectNode, Placement
from .cables import cable_items, is_cable
from .closure import rail_pairs
from .colours import BASE_COLOURS, COLOUR_GRAMMAR, RESERVED_COLOURS, split_colour
from .connectivity import Conductor, Mate, Net
from .contacts import LinkState, Throws, changeover_throws, link_state
from .core import Function, Item, Port, Unit, UnitRelease
from .document import Document
from .enums import (
    Aspect,
    ConductorKind,
    ConductorMark,
    Current,
    DocumentPreset,
    Earthing,
    Energy,
    FunctionKind,
    Gender,
    LinkKind,
    LinkRest,
    NetClass,
    PageKind,
    PartCategory,
    PoleSide,
    PortRole,
    PowerKind,
    ProtectionType,
    SignalType,
)
from .facets import (
    AssignedDesignationFacet,
    AssignedUnitTagFacet,
    BoundaryValuesFacet,
    CableFacet,
    CableProductFacet,
    ConnectorFacet,
    CoreFacet,
    FootprintFacet,
    OperatingFacet,
    PartRatingFacet,
    PcbFacet,
    PlcBindingFacet,
    PlcChannelFacet,
    PlcRequestFacet,
    RatingFacet,
    ReservedDesignationFacet,
    ScalingFacet,
    SupplyFacet,
    TerminalFacet,
    WireFacet,
)
from .instantiate import PartBundle, instantiate
from .markings import (
    Pole,
    function_poles,
    is_pole_link,
    marking_key,
    pole_order,
    port_order_key,
    unlinked_poles,
)
from .membership import crosses_unit
from .project import Project
from .rating_readers import (
    boundary_operating,
    boundary_rating,
    function_operating,
    function_rating,
    part_rating,
)
from .ratings import Operating, Rating, effective_rating
from .revision import Revision
from .supply_system import Rail, SupplySystem, rail_phase_problem
from .tables import (
    Boundary,
    UnusedBoundary,
    aspect_nodes,
    boundaries,
    conductors,
    documents,
    facet_subject,
    facets_of,
    function_templates,
    functions,
    internal_links,
    items,
    mates,
    nets,
    part_libraries,
    parts,
    placements,
    port_templates,
    ports,
    projects,
    revisions,
    supply_systems,
    unit_releases,
    units,
    unused_boundaries,
)
from .templates import FunctionTemplate, InternalLink, Part, PartLibrary, PortTemplate
from .unit_by_name import unit_name_unresolved, units_named
from .unit_index import unit_index
from .validators import ALL_VALIDATORS

# The kernel knows only `core`; the layers above name the rest, once, in this order. A
# reference may point at the same namespace or an earlier one (decision 0009).
register_namespaces("facet", "layout")

__all__ = [
    "ALL_VALIDATORS",
    "BASE_COLOURS",
    "COLOUR_GRAMMAR",
    "RESERVED_COLOURS",
    "Aspect",
    "AspectNode",
    "AssignedDesignationFacet",
    "AssignedUnitTagFacet",
    "Boundary",
    "BoundaryValuesFacet",
    "CableFacet",
    "CableProductFacet",
    "Conductor",
    "ConductorKind",
    "ConductorMark",
    "ConnectorFacet",
    "CoreFacet",
    "Current",
    "Document",
    "DocumentPreset",
    "Earthing",
    "Energy",
    "FootprintFacet",
    "Function",
    "FunctionKind",
    "FunctionTemplate",
    "Gender",
    "InternalLink",
    "Item",
    "LinkKind",
    "LinkRest",
    "LinkState",
    "Mate",
    "Net",
    "NetClass",
    "Operating",
    "OperatingFacet",
    "PageKind",
    "Part",
    "PartBundle",
    "PartCategory",
    "PartLibrary",
    "PartRatingFacet",
    "PcbFacet",
    "Placement",
    "PlcBindingFacet",
    "PlcChannelFacet",
    "PlcRequestFacet",
    "Pole",
    "PoleSide",
    "Port",
    "PortRole",
    "PortTemplate",
    "PowerKind",
    "Project",
    "ProtectionType",
    "Rail",
    "Rating",
    "RatingFacet",
    "ReservedDesignationFacet",
    "Revision",
    "ScalingFacet",
    "SignalType",
    "SupplyFacet",
    "SupplySystem",
    "TerminalFacet",
    "Throws",
    "Unit",
    "UnitRelease",
    "UnusedBoundary",
    "WireFacet",
    "aspect_nodes",
    "boundaries",
    "boundary_operating",
    "boundary_rating",
    "cable_items",
    "changeover_throws",
    "conductors",
    "crosses_unit",
    "documents",
    "effective_rating",
    "facet_subject",
    "facets_of",
    "function_operating",
    "function_poles",
    "function_rating",
    "function_templates",
    "functions",
    "instantiate",
    "internal_links",
    "is_cable",
    "is_pole_link",
    "items",
    "link_state",
    "marking_key",
    "mates",
    "nets",
    "part_libraries",
    "part_rating",
    "parts",
    "placements",
    "pole_order",
    "port_order_key",
    "port_templates",
    "ports",
    "projects",
    "rail_pairs",
    "rail_phase_problem",
    "revisions",
    "split_colour",
    "supply_systems",
    "unit_index",
    "unit_name_unresolved",
    "unit_releases",
    "units",
    "units_named",
    "unlinked_poles",
    "unused_boundaries",
]
