"""The cable engine's golden (CT5-LINK P0): every cable block record of the invented models.

One file, `tests/golden/cable_blocks.txt`, holds for each model and each (reading, subject) either
`no block` or the block's boxes, end boxes and core wires. It is regenerated by
`just regen-goldens layout`, never by hand, and any change to a drawn block moves it. The pump
station's records are compared by a tool outside the repo (the examples are another repository).
"""

from dataclasses import fields
from pathlib import Path
from typing import Any

import pytest
from cable_models import MODELS

from fransys_layout.engines.cable.read.subjects import block_pairs
from fransys_model.kernel import Id, Model
from fransys_model.layout import CableBlock, CableBox, CoreWire, EndBox, layout_of

_GOLDEN = Path(__file__).resolve().parent.parent / "golden" / "cable_blocks.txt"
_SKIP = {"id", "key", "produced_by", "ext", "block"}


@pytest.fixture
def regenerate(request: pytest.FixtureRequest) -> bool:
    """True under `--regenerate-golden`: the golden is rewritten instead of compared."""
    return bool(request.config.getoption("--regenerate-golden"))


def _name(model: Model, found: Id[Any]) -> str:
    record = model.tables[found.kind].get(found)
    return "/".join(record.key) if record is not None else found.value


def _show(model: Model, value: Any) -> str:
    if isinstance(value, Id):
        return _name(model, value)
    if isinstance(value, tuple):
        return "[" + " ".join(_show(model, v) for v in value) + "]"
    if hasattr(value, "index") and hasattr(value, "x"):  # a PinCell or a RoutePoint
        return "(" + ",".join(_show(model, getattr(value, f.name)) for f in fields(value)) + ")"
    return str(value)


def _line(model: Model, record: Any) -> str:
    shown = (f"{f.name}={_show(model, getattr(record, f.name))}" for f in fields(record))
    return (
        "  "
        + record.__class__.__name__
        + " "
        + " ".join(
            text for text, f in zip(shown, fields(record), strict=True) if f.name not in _SKIP
        )
    )


def _block_lines(model: Model, head: CableBlock) -> list[str]:
    lines = [_line(model, head)]
    for kind in (CableBox, EndBox, CoreWire):
        found = [r for r in layout_of(model, kind).values() if r.block == head.id]
        lines += [_line(model, r) for r in sorted(found, key=lambda r: r.key)]
    return lines


def _dump(model: Model) -> list[str]:
    heads = {(h.subject, h.unit): h for h in layout_of(model, CableBlock).values()}
    lines = []
    for unit, subject in block_pairs(model):
        where = "absolute" if unit is None else "unit " + _name(model, unit)
        lines.append(f"{_name(model, subject)} [{where}]")
        head = heads.get((subject, unit))
        lines += _block_lines(model, head) if head else ["  no block"]
    return lines


def golden_text() -> str:
    """The golden's text: each model's name, then its blocks."""
    out: list[str] = []
    for name, build in MODELS.items():
        out += [f"== {name}", *_dump(build().model)]
    return "\n".join(out) + "\n"


def test_cable_blocks_match_the_golden(*, regenerate: bool) -> None:
    """Any change to a drawn cable block, or to which cables draw, moves this file.

    Probe: a patch to `write/records.py::_points` shifting one wire's point by one grid unit.
    """
    actual = golden_text()
    if regenerate:
        _GOLDEN.write_text(actual, encoding="utf-8", newline="\n")
    assert actual == _GOLDEN.read_text(encoding="utf-8")
