"""Write `_vendor_cytoscape.py` from a downloaded `cytoscape.min.js`; no network (see the README).

Usage: `uv run python packages/fransys-overview/scripts/vendor_cytoscape.py <min.js> <version>`.
"""

import ast
import hashlib
import sys
from pathlib import Path

PACKAGE = Path(__file__).resolve().parent.parent / "src" / "fransys_overview"
TARGET = PACKAGE / "_vendor_cytoscape.py"
INDENT = "        "
MAX_LINE = 100
MAX_WIDTH = MAX_LINE - len(INDENT) - 3  # the two quotes and the comma

_HEADER = '''"""Cytoscape.js {version}, vendored; GENERATED by the vendoring script, do not edit.

`CYTOSCAPE_MIN_JS` is `dist/cytoscape.min.js` of the npm package `cytoscape@{version}` as
downloaded, byte for byte (MIT licence: `LICENSE-cytoscape.txt`). `CYTOSCAPE_SHA256` is the sha256
of those bytes; a test recomputes it from the constant.
"""

from typing import Final

CYTOSCAPE_VERSION: Final[str] = "{version}"
CYTOSCAPE_SHA256: Final[str] = "{sha256}"
CYTOSCAPE_MIN_JS: Final[str] = "".join(
    [
'''

_FOOTER = """    ]
)
"""

_NAMED = {"\\": "\\\\", "\n": "\\n", "\r": "\\r", "\t": "\\t"}


def _escape(char: str, quote: str) -> str:
    """One character as it is written inside a `quote`-quoted Python literal, ASCII only."""
    if char == quote:
        return "\\" + char
    if char in _NAMED:
        return _NAMED[char]
    code = ord(char)
    if 32 <= code < 127:  # noqa: PLR2004 -- printable ASCII
        return char
    if code < 256:  # noqa: PLR2004 -- one byte
        return f"\\x{code:02x}"
    if code < 65536:  # noqa: PLR2004 -- one UTF-16 unit
        return f"\\u{code:04x}"
    return f"\\U{code:08x}"


def _literal(chunk: str) -> str:
    """`chunk` as a literal in the quote style `ruff format` keeps: double unless more `"` in it."""
    quote = "'" if chunk.count('"') > chunk.count("'") else '"'
    return quote + "".join(_escape(char, quote) for char in chunk) + quote


def _chunks(source: str) -> list[str]:
    """`source` cut so that each piece fits a line even with every quote escaped."""
    pieces: list[str] = []
    piece: list[str] = []
    width = 0
    for char in source:
        size = len(_escape(char, '"'))
        if width + size > MAX_WIDTH:
            pieces.append("".join(piece))
            piece, width = [], 0
        piece.append(char)
        width += size
    pieces.append("".join(piece))
    return pieces


def _module(source: str, version: str, sha256: str) -> str:
    lines = [f"{INDENT}{_literal(chunk)}," for chunk in _chunks(source)]
    if max(len(line) for line in lines) > MAX_LINE:
        msg = f"a chunk needs more than {MAX_LINE} columns"
        raise SystemExit(msg)
    return _HEADER.format(version=version, sha256=sha256) + "\n".join(lines) + "\n" + _FOOTER


def _read_back(text: str) -> str:
    """The string constant of the generated module, from its syntax tree (nothing is run)."""
    for node in ast.walk(ast.parse(text)):
        if isinstance(node, ast.List):
            return "".join(ast.literal_eval(element) for element in node.elts)
    msg = "no list of chunks in the generated module"
    raise SystemExit(msg)


def main(argv: list[str]) -> int:
    """Read the file, write the module, and check it reproduces the file's bytes."""
    if len(argv) != 2:  # noqa: PLR2004 -- the path and the version
        sys.stdout.write(f"usage: {Path(__file__).name} <cytoscape.min.js> <version>\n")
        return 2
    raw = Path(argv[0]).read_bytes()
    version = argv[1]
    source = raw.decode("utf-8")
    if source.encode("utf-8") != raw:
        msg = "the file does not survive a UTF-8 round trip"
        raise SystemExit(msg)
    sha256 = hashlib.sha256(raw).hexdigest()
    text = _module(source, version, sha256)
    if _read_back(text).encode("utf-8") != raw:
        msg = "the generated module does not reproduce the file"
        raise SystemExit(msg)
    TARGET.write_text(text, encoding="utf-8", newline="\n")
    sys.stdout.write(f"wrote {TARGET}: cytoscape {version}, {len(raw)} bytes, sha256 {sha256}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
