"""Stages layer: pure, engine-agnostic steps over small frozen values.

Refs: foundations.md 3, stages.md 6.
"""

from .columns import boundary_key, columns_from_chains, replica_key
from .cutpages import cut_pages
from .labels import place_slot_labels
from .partition import column_widths, partition
from .place import place
from .references import links
from .resolve import resolve
from .route import route
from .types import (
    ROLE_ORDER,
    BoxFeed,
    Cell,
    Chain,
    ChainEntry,
    Column,
    ColumnWidth,
    Connection,
    DrawnFunction,
    DrawnPort,
    FedPin,
    FunctionSpec,
    GroupInfo,
    GroupSet,
    Handle,
    KindRoles,
    LabelKind,
    LabelRequest,
    Layout,
    LinkCase,
    LinkDecision,
    LinkMarker,
    LocationInfo,
    MarkerSide,
    NetGroup,
    OrderHint,
    PageHints,
    PagePlan,
    PlacedFunction,
    PlacedLabel,
    PlannedColumn,
    PlannedGroup,
    PolePair,
    PortRef,
    PortSpec,
    PowerEnd,
    Profile,
    Rail,
    RailEnd,
    RequestPartner,
    Role,
    Route,
    RoutePoint,
    SheetFormat,
    SymbolChoice,
    SymbolRule,
    UnitInfo,
)

__all__ = (
    "ROLE_ORDER",
    "BoxFeed",
    "Cell",
    "Chain",
    "ChainEntry",
    "Column",
    "ColumnWidth",
    "Connection",
    "DrawnFunction",
    "DrawnPort",
    "FedPin",
    "FunctionSpec",
    "GroupInfo",
    "GroupSet",
    "Handle",
    "KindRoles",
    "LabelKind",
    "LabelRequest",
    "Layout",
    "LinkCase",
    "LinkDecision",
    "LinkMarker",
    "LocationInfo",
    "MarkerSide",
    "NetGroup",
    "OrderHint",
    "PageHints",
    "PagePlan",
    "PlacedFunction",
    "PlacedLabel",
    "PlannedColumn",
    "PlannedGroup",
    "PolePair",
    "PortRef",
    "PortSpec",
    "PowerEnd",
    "Profile",
    "Rail",
    "RailEnd",
    "RequestPartner",
    "Role",
    "Route",
    "RoutePoint",
    "SheetFormat",
    "SymbolChoice",
    "SymbolRule",
    "UnitInfo",
    "boundary_key",
    "column_widths",
    "columns_from_chains",
    "cut_pages",
    "links",
    "partition",
    "place",
    "place_slot_labels",
    "replica_key",
    "resolve",
    "route",
)
